spring.application.name=E-Commerce

spring.datasource.url=jdbc:postgresql://localhost:5432/E-CommerceDB
spring.datasource.username=postgres
spring.datasource.password=Kashyap_2323
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=jheij3iu894urnfjnio45utu203i23irojifhijotu7348qu33($ui839rufu3984ur
jwt.expiration=86400000